### ISSUE TITLE
VMware Collector

### ISSUE THREAD

**Issue by exbane** [micelshima/notes#1]
@micelshima - I couldnt figure out any other way to contact you.. I saw your dashboards for VMware Storage monitoring on Grafana.net and was curious as to what vSphere collector you were using to get the data injested into InfluxDB? I've been using vsphere-influxdb-go.

**Comment by micelshima** [comment]
Hello,

I use powershell to gather all my metrics as my monitoring services run in Windows Servers.

I send http messages to influxdb server port 8086 with cmdlet invoke-webrequest in my powershell scripts. (this cmdlet is available since powershell 3.0 and is similar to 'curl')

vmware for example published a powershell module called powerCLI which can connect to vCenter and/or the hosts and get all the metrics you want.

so I schedule  tasks every one or two hours in vCenter Server (Windows 2008 R2 with Powershell 4.0 installed)


* vmcreationdeletion2influxdb.ps1
* vmdatastores2influxdb.ps1
* vmIOPS2influxdb.ps1
* vmlatency2influxdb.ps1

All of them use a module I have writen to deal with influxdb
* influxDBfunctions.psm1
You need to change the URL inside this module with your influxdb server.

Here is the link with these and all my other influxDB scripts, i hope you find it useful: https://1drv.ms/u/s!Ap0HiMl_g1h3oiVWKZAj7KEH6K6V<https://1drv.ms/u/s%21Ap0HiMl_g1h3oiVWKZAj7KEH6K6V>
[https://r1.res.office365.com/owa/prem/images/dc-zip_40.png]<https://1drv.ms/u/s%21Ap0HiMl_g1h3oiVWKZAj7KEH6K6V>
Grafana-InfluxDB.zip<https://1drv.ms/u/s%21Ap0HiMl_g1h3oiVWKZAj7KEH6K6V>
Se ha compartido a través de OneDrive





Regards
Mikel Valencia


________________________________
De: exbane <notifications@github.com>
Enviado: viernes, 13 de enero de 2017 13:25
Para: micelshima/notes
Cc: micelshima; Mention
Asunto: [micelshima/notes] VMware Collector (#1)


@micelshima<https://github.com/micelshima> - I couldnt figure out any other way to contact you.. I saw your dashboards for VMware Storage monitoring on Grafana.net and was curious as to what vSphere collector you were using to get the data injested into InfluxDB? I've been using vsphere-influxdb-go.

-

**Comment by exbane** [comment]
@micelshima Thank you very much! I'm taking a look through your scripts now - they look great!

**Comment by micelshima** [comment]
@exbane I have uploaded all my influxDB powershell scripts and module here:
https://github.com/micelshima/InfluxDB-Powershell-Module
